<?php 

    $config = Zend_Registry::get('config'); 
    
    $year = $config->project->year;
    
?>


<style type="text/css">
    /*#index-content {margin-bottom:15px;padding:10px;width:918px;border:1px solid #0088ce;-moz-box-shadow: 0 0 5px #ddd;-webkit-box-shadow: 0 0 5px#ddd;box-shadow: 0 0 5px #ddd;}*/
    #index-content {margin-bottom:15px;padding:10px;width:918px;border:1px solid #c8c8c8;-moz-box-shadow: 0 0 5px #ddd;-webkit-box-shadow: 0 0 5px#ddd;box-shadow: 0 0 5px #ddd;}
    #index-image-1 {}
    #index-image-2 {margin-left:525px;}
</style>


<script type="text/javascript">
    
;(function($){
 
 
    $(document).ready(function(){
        
        $("#submit-logon").button().click(function() {
            $("#form-logon").submit();
        });
        
        
        var pos = 0;
        var a = $("#side-list").find("a");
        a.each(function(i){            
            if (i <= pos) {
                $(this).css({"color":"#333333", "font-weight":"normal"});        
            }
            if (i == pos) {
                $(this).css({"color":"#336699", "font-weight":"bold"});        
            }
            if (i > pos) {
                $(this).css({"color":"#333333", "font-weight":"normal"});        
            }
        });
        
        $("#form-logon").validate();
        
    });
   
})(jQuery);
    
</script>

<div id="index-content">

    <!--
    <img src="/images/bmw-image-01-crop-01.jpg" alt="" id="index-image-1"/>
    <img src="/images/bmw-image-2014-01-crop.png" alt="" id="index-image-1"/>
    -->
    <img src="/images/2015/2015-bmw-m4.png" alt="" id="index-image-1"/>

    <h3>Home</h3>
    
    <p>        
        We are pleased that your valued team member has been selected to attend the 2015 BMW Aftersales Recognition Ride-and-Drive Event in Thermal, California.  We look forward to providing an unforgettable experience at BMW Performance Center West.
    </p>
    
    <p>
        <b>Event Dates:</b><br>
        All Regions:  September 21-22  (arrive on 9/21 for reception/dinner)
    </p>
    
    <p>
        <!--
        The event will begin with a dinner upon arrival followed by a day at the BMW Performance Center West and a street drive through the hills and desert of Southern California.
        -->
        The event will begin with a dinner upon arrival followed by a day at the BMW Performance Center West.
    </p>
        
    <p>
        Please begin the registration process below to confirm his/her attendance:
    </p>

    <form action="/" method="post" id="form-logon">
    <table width="50%" align="" border="0">
        <tr>
            <td colspan="3" align="center"><span class="site-label-3"><?php echo $this->message;?></span></td>
        </tr>
        <tr>
            <td><span class="site-label-1">Your email address:</span></td>
            <td><input type="text" class="site-text-1 required" name="email" id="email" value="" /></td>
            <td>&nbsp;</td>                                
        </tr>
        <tr>
            <td><span class="site-label-1">Password:  <span style="color:#1c68d1;">recognition</span></span></td>
            <td><input type="password" class="site-text-1 required" name="password" id="password" value="" /></td>
            <td>
                <!--
                <span class="site-label-2">(e.g. QT12345)
                </span>
                -->
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td align="left"><button class="" name="" id="submit-logon">Submit</button></td>
            <td>&nbsp;</td>
        </tr>
    </table>
    </form>
    
</div>

