<?php 

    $config = Zend_Registry::get('config');    

?>


<style type="text/css">
    #index-content {margin-bottom:15px;padding:10px;width:918px;border:1px solid #ccc;-moz-box-shadow: 0 0 5px #ddd;-webkit-box-shadow: 0 0 5px#ddd;box-shadow: 0 0 5px #ddd;}
    #index-image-1 {}
    #index-image-2 {margin-left:525px;}
</style>


<script type="text/javascript">
    
;(function($){
 
    $(document).ready(function(){
        
        $("#submit-logon").button().click(function() {
            $("#form-logon").submit();
        });
        
        
        var pos = 0;
        var a = $("#side-list").find("a");
        a.each(function(i){            
            if (i <= pos) {
                $(this).css({"color":"#333333", "font-weight":"normal"});        
            }
            if (i == pos) {
                $(this).css({"color":"#336699", "font-weight":"bold"});        
            }
            if (i > pos) {
                $(this).css({"color":"#333333", "font-weight":"normal"});        
            }
        });
        
        $("#form-logon").validate();
        
    });
   
})(jQuery);
    
</script>

<div id="index-content">

    <!--
    <img src="/images/bmw-image-01-crop-01.jpg" alt="" id="index-image-1"/>
    -->
    <img src="/images/bmw-image-2014-01-crop.png" alt="" id="index-image-1"/>

    <h3>Home</h3>
    
    <p>
        On-line registration for the Aftersales Recognition Ride-and-Drive Event at the BMW Performance Center in Greer, South Carolina is not currently open.
    </p>
    
    <!--
    <p>
        Please contact <?php echo $config->site->admin->name;?> at 201-571-5172 to register by phone.
    </p>
    -->
    
    <p>
        For registration assistance please contact <?php echo $config->site->admin->name;?> at <a href="mailto:<?php echo $config->site->admin->email;?>" class="site-link-2"><?php echo $config->site->admin->email;?></a> or 201-307-4051.
    </p>

    <p>
        <b>Event Dates:</b><br>
        Southern and Western Regions:  September 9th (arrive on 9/8 for reception/dinner)<br>
        Central and Eastern Regions:  September 10th (arrive on 9/9 for reception/dinner)<br>
    </p>
        
    
    
</div>

