<style type="text/css">
    #index-content {margin-bottom:15px;padding:10px;width:918px;border:1px solid #c8c8c8;-moz-box-shadow: 0 0 5px #ddd;-webkit-box-shadow: 0 0 5px#ddd;box-shadow: 0 0 5px #ddd;}
    #index-image-1 {}
    #index-image-2 {margin-left:525px;}
        
    #accommodations {padding-left:10px;font-size:12px;color:#1c68d1;font-weight:normal;text-decoration:none;padding-left:10px;}
    a#accommodations:link {color:#1c68d1;}
    a#accommodations:hover {color:#333333;}

    .agenda-header {font-weight:normal;text-decoration:none;}
    .agenda-time {padding-right: 50px;}
    .agenda-time-list {display: inline-block; width: 185px;}
    .agenda-unordered-list {font-weight: bold;}
    
</style>

<script type="text/javascript">
    
;(function($){
 
    $(document).ready(function(){
                
        var pos = 1;
        var a = $("#side-list").find("a");
        a.each(function(i){            
            if (i <= pos) {
                $(this).css({"color":"#333333", "font-weight":"normal"});        
            }
            if (i == pos) {
                $(this).css({"color":"#0088ce", "font-weight":"bold"});        
            }
            if (i > pos) {
                $(this).css({"color":"#333333", "font-weight":"normal"});        
            }
        });        
                
    });
   
})(jQuery);

</script>

<div id="index-content">

    <!--
    <img src="/images/bmw-image-03-crop-01.jpg" alt="" id="index-image-1"/>
    <img src="/images/bmw-image-2014-02-crop.png" alt="" id="index-image-1"/>
    <img src="/images/2015/DQ6U4072.png" alt="" id="index-image-1"/>
    -->
    <img src="/images/2015/IMG_0026-contrasted.png" alt="" id="index-image-1"/>
    

    <h3>Agenda <a href="/accommodations" id="accommodations">Hotel Accommodations</a></h3>

    <div class="agenda-header">September 21</div>
    
    <p>
        <b><span class="agenda-time">9:00 am - 6:00 pm</span> Arrival / Hotel Check-In / Registration</b><br>
        <ul>
            <li>The local airport is Palm Springs International (PSP) in Palm Springs, CA</li>
            <li>Ground transportation provided between PSP and La Quinta Resort (35 minutes apart)</li>
            <li>Plan to arrive at PSP no later than 5:00PM  in order to allow time to register and check-in at the hotel prior to dinner</li>
            <li>Personalized agendas provided upon arrival.</li>
        </ul>
    </p>
    
    <p>
        <b><span class="agenda-time">6:30 pm - 8:30 pm</span> Reception and Dinner</b><br>
        <ul>
            <li>Meet and greet</li>
            <li>Guest speakers</li>
            <li>Business casual attire</li>
        </ul>
    </p>
    
    <br>
    <div class="agenda-header">September 22</div>
    
    <p>
        <b><span class="agenda-time">7:00 am - 8:45 am</span> Breakfast (provided in La Quinta Ballroom) / Check-out</b><br><br>
        
        <b><span class="agenda-time">8:00 am</span> Group A: Bus transport to the BMW Performance Center West</b><br>
        <b><span class="agenda-time">9:00 am</span> Group B: Bus transport to the BMW Performance Center West</b><br>
        
        <p></p>
        <b>Morning Rotation</b><br>
        <ul class="agenda-unordered-list">
            <li><div class="agenda-time-list">8:30 am - 11:30 am</div> Group A:  Performance Center West Driving</li>
            <li><div class="agenda-time-list">9:30 am - 12:30 pm</div> Group B:  Performance Center West Driving</li>
        </ul>
    
        <b>Lunch</b><br>
        <ul class="agenda-unordered-list">
            <li><div class="agenda-time-list">11:30 am - 12:30 pm</div>Group A</li>
            <li><div class="agenda-time-list">12:30 pm -  1:30 pm</div>Group B</li>
        </ul>
        
        <b>Afternoon Rotation</b><br>
        <ul class="agenda-unordered-list">
            <li><div class="agenda-time-list" style="">12:45 pm - 3:30 pm</div> Group A:  Performance Center West Driving</li>
            <li><div class="agenda-time-list" style="">1:45 pm - 4:30 pm</div> Group B:  Performance Center West Driving</li>
        </ul>
        
        <b><span class="agenda-time" style="padding-right:103px;">3:30 pm</span> Group A departs for PSP Airport followed by a stop at the hotel</b><br>
        <b><span class="agenda-time" style="padding-right:103px;">4:30 pm</span> Group B departs for PSP Airport followed by a stop at the hotel</b><br>
    </p>

    <p>*As this is a full program, please do not book flights departing earlier than 6:30pm.</p>
    
</div>

