
<?php
$config = Zend_Registry::get('config');
$title = $config->project->title;
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle($title);

echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title><?php echo $title;?></title>

        <!-- shortcut icon -->
        <link rel="shortcut icon" type="image/x-icon" href="/images/bmwicon.gif"></link>

        <!-- css files -->
        <link href="/css/site.css" rel="stylesheet" type="text/css"></link>                
        <link href="/css/custom-theme/jquery-ui-1.9.2.custom.css" rel="stylesheet" type="text/css"></link>                
        <link href="/css/jquery.ui.timepicker.css" rel="stylesheet" type="text/css"></link>        
        <link href="/js/jqGrid/css/ui.jqgrid.css" rel="stylesheet" type="text/css"></link>

        <!-- DateJS -->
        <script type="text/javascript" src="/js/datejs/build/date.js"></script>        
                
        <!-- js files -->
        <script type="text/javascript" src="/js/jquery.rs.js"></script>        

        <script type="text/javascript" src="/js/jquery-1.8.3.js"></script>
                
        <!--[if gte IE 9]><!-->
        <script type="text/javascript" src="/js/jquery-ui-1.9.2.custom.min.js"></script>
        <!--<![endif]-->        
                
        <!--[if lt IE 9]>
        <script type="text/javascript" src="/js/jquery-ui-1.8.20.custom.min.js"></script>
        <![endif]-->        
        
        <script type="text/javascript" src="/js/jquery.validate.js"></script>
        <script type="text/javascript" src="/js/jquery.maskedinput-1.3.js"></script>
        <script type="text/javascript" src="/js/jquery.inputmask.bundle.js"></script>
        
        <script type="text/javascript" src="/js/jquery.ui.timepicker.js"></script>
                       
        <!-- jqGrid base js  -->
        <script type="text/javascript" src="/js/jqGrid/js/i18n/grid.locale-en.js" ></script>
        <script type="text/javascript" src="/js/jqGrid/js/jquery.jqGrid.min.js"></script>

        <!-- jqGrid extra js  -->
        <script type="text/javascript" src="/js/jqGrid/src/grid.base.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.celledit.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.common.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.custom.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.filter.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.formedit.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.grouping.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.import.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.inlinedit.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.jqueryui.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.subgrid.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.tbltogrid.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/grid.treegrid.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/jqDnR.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/jqModal.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/jquery.fmatter.js"></script>
        <script type="text/javascript" src="/js/jqGrid/src/JsonXml.js"></script>  
        
        <!-- plupload -->
        <link href="/plupload-2.1.2/js/jquery.ui.plupload/css/jquery.ui.plupload.css" rel="stylesheet" type="text/css"></link>        
        <script type="text/javascript" src="/plupload-2.1.2/js/plupload.full.min.js"></script>
        <script type="text/javascript" src="/plupload-2.1.2/js/jquery.ui.plupload/jquery.ui.plupload.min.js"></script>
                
    </head>
    <body>

        <div id="content">
            <div id="tc"><?php include('top.phtml');?></div>
            <div id="lc"><?php echo $this->layout()->content; ?></div>
            <div id="bc"><?php include('bottom.phtml');?></div>
        </div>

        <div id="loader" style="display: none;"></div>

    </body>
    
</html>

