<h3>User Detail</h3>

<table width="100%" align="center" style="padding:15px;">
    <tr>
        <td><span class="site-label-1">ID:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["id"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Date Created:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["date_created"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Last Updated:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["last_updated"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">User:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["user"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Active:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["active"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">User ID:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["user_id"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Password:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["password"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Role ID:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["role_id"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">First Name:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["first_name"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Last Name:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["last_name"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Email:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["email"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Q Number:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["q_number"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Employee Number:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["emp_no"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Title:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["title"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Check-in Date:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["check_in_date"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Check-out Date:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["check_out_date"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Early Check-in:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["early_check_in"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Late Check-out:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["late_check_out"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Transportation:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["transportation"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Hotel:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["hotel"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Room Type:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["room_type"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Occupancy:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["occupancy"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Guest Type:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["guest_type"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Guest Name:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["guest_name"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Registration Status:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["registration_status"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Nickname:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["nickname"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Center:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["center"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Region:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["region"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Gender:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["gender"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Telephone:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["telephone"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Emergency Contact:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["emergency_contact"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Emergency Telephone:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["emergency_telephone"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Dietar Restrictions:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["dietary_restrictions"];?></span></td>
    </tr>
</table>