<style type="text/css">
    #index-container {position:relative;margin-bottom:15px;}
    #index-content {padding:10px;width:670px;border:1px solid #ccc;-moz-box-shadow: 0 0 5px #ddd;-webkit-box-shadow: 0 0 5px#ddd;box-shadow: 0 0 5px #ddd;}
    #index-sub-text {padding:10px;}
    #index-image-1 {}
    #index-image-2 {margin-left:525px;}
</style>
    
<div id="index-container">
    
    <table>
        <tr>
            <td valign="top"><?php echo $this->partial('all/side.phtml');?></td>
            <td valign="top">
                
                <div id="index-content">
                    <?php include('index-content.phtml');?>
                </div>
                
            </td>
        </tr>
    </table>
        
</div>

